name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:6.2
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t scoring_app .

    - name: Run tests
      env:
        REDIS_HOST: localhost
        REDIS_PORT: 6379
      run: docker run --network host scoring_app pytest homework/tests/